-- ============================================================================
-- TugasKu: Skrip Inisialisasi Tabel Supabase PostgreSQL
-- Mata Kuliah Semester 3 D4 Sistem Informasi Bisnis (Polinema)
-- 
-- Cara Penggunaan:
-- 1. Buka dashboard Supabase (https://supabase.com/dashboard)
-- 2. Pilih Project Anda -> Masuk ke menu "SQL Editor"
-- 3. Paste seluruh skrip di bawah ini dan klik "Run"
-- ============================================================================

-- 1. Buat Tabel tugas_kuliah
CREATE TABLE IF NOT EXISTS public.tugas_kuliah (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject TEXT NOT NULL,
    name TEXT NOT NULL,
    deadline TIMESTAMPTZ NOT NULL,
    submission TEXT NOT NULL,
    is_done BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Aktifkan Row Level Security (RLS)
ALTER TABLE public.tugas_kuliah ENABLE ROW LEVEL SECURITY;

-- 3. Buka Akses Penuh (Read, Insert, Update, Delete) untuk Public/Anon
CREATE POLICY "Public tugas access" 
ON public.tugas_kuliah 
FOR ALL 
USING (true) 
WITH CHECK (true);

-- 4. Aktifkan Real-Time Live Sync untuk Tabel tugas_kuliah
ALTER PUBLICATION supabase_realtime ADD TABLE public.tugas_kuliah;
